version: 2
updates:
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: monthly
    groups:
      minor-and-patch-version-updates:
        update-types:
          - minor
          - patch
  - package-ecosystem: pub
    directory: "/example"
    schedule:
      interval: monthly
    groups:
      minor-and-patch-version-updates:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    groups:
      minor-and-patch-version-updates:
        update-types:
          - minor
          - patch
