name: Publish to pub.dev

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
      - run: dart pub get
      - run: dart pub publish --force


  notify-slack-failure:
    runs-on: ubuntu-latest
    needs: [ publish ]
    if: failure()
    steps:
      - uses: seatsio/seatsio-github-actions/slack-notify-clientlib-release-failure@v1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
